### ISSUE TITLE
Maybe Gulp as an option?

### ISSUE THREAD

**Issue by juliancwirko** [juliancwirko/generator-zf5#10]
Like in title...

**Comment by ppowalowski** [comment]
Is anyone working in this already?
When porting to gulp consider the usage of [browser-sync](https://github.com/BrowserSync/browser-sync)

This tool blew my mind ;-)

I propose to kick this off if I have spare time left (probable somwhere in may). 

Cheers

**Comment by juliancwirko** [comment]
Hi, there are no works on it. It will be great if you could take care of it. Gulp should be an option to choose. And yes, I would like to see Browser-sync here. I think it could be replacement for LiveReload, am I right?

Anyway, I am thinking of renaming generator to something like 'generator-foundation-for-sites' and it needs general cleanup for version 1.0. Soon there will be Foundation 6.0 so we will be able to have smooth transition (I hope).

**Comment by ppowalowski** [comment]
Yesss browser-sync is kind of an universal live-reload solution. It's awesome due to site proxying capability. So one can use it with any project. It also provides fancy functionality as scroll syncing across browsers.

I'll keep this issue in mind. Currently I'm working on a differently based ecommerce project so there's not much time left for this purpose. I'll come back to this as soon as I feel having time for doing it in one sprint.

siema ;-)

**Comment by juliancwirko** [comment]
Yeah, time.. time is what I need here too ;) 

But I will try to find some time for cleaning and preparation for 1.0.0 and then we could try to add gulp and browser-sync.

Dzięki :)

**Comment by juliancwirko** [comment]
https://github.com/juliancwirko/generator-zf5/issues/41

**Comment by CharlieGreenman** [comment]
Hey guys, not sure if this helps, but just finished this build for gulp [https://github.com/CharlieGreenman/Gulp-with-foundation-and-sass] . It uses browser-sync btw. I'm just terrible at Yeoman, and am doing that right now. Hopefully, I can get this one done.

**Comment by ppowalowski** [comment]
Thank you Charlie,
Definitely there will by a gulp version released! Thanks.

**Comment by ppowalowski** [comment]
Did anyone look at this one?
https://github.com/niallobrien/generator-gulp-foundation

**Comment by peterankelein** [comment]
That was actually the first one I looked at when testing Foundation generators but when scaffolding, it throws a bunch of rebuild errors on the two win machines I've tried it on. There are apparently fixes like what's shown here: https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/ but it felt like a lot of extra effort and installs considering both gulp-webapp and Julian's ZF5 generator work right out of the gate. I just started a huge project where everything's being built off of a Foundation base so I've started with gulp-webapp and have it running Foundation and Font-Awesome. Been recently looking at ZF5 and I like how it's organized so have been mulling over combining some of it. Biggest hurdle seems to be interpreting what's going on on in the gulp-webapp gulpfile when actually doing a build.

**Comment by juliancwirko** [comment]
Thanks for the info. I wish I had some more time for this one :/ 
I plan to refresh generator when Foundation 6 will be ready.

**Comment by peterankelein** [comment]
Yeah, time is always the issue. I'm new to creating/forking generators but I have thought about forking gulp-webapp or yours and mucking about to see if I could incorporate the best (in my mind) features of the two.

**Comment by CharlieGreenman** [comment]
Hmm, maybe I'll take a crack at it. For me, it's really do I see Yeoman as being beneficial enough to make a yeoman generator, as opposed to cloning the build, running sudo npm install, and running bower install. Btw updated the gulp build here https://github.com/CharlieGreenman/Gulp-with-foundation-and-sass

**Comment by juliancwirko** [comment]
Closed for now. You can read more here: https://github.com/juliancwirko/generator-zf5/issues/41#issuecomment-146167374
