### ISSUE TITLE
Jade templates - feedback needed

### ISSUE THREAD

**Issue by juliancwirko** [juliancwirko/generator-zf5#19]
From version 0.8.0 you can use Jade templates.. 
Any feedback will be very appreciated.

Thanks.

**Comment by Ernesto-Valdes** [comment]
I think that the best approach for integrating other popular technologies (Jade, Handlebars, ...) is to create recipes. This is already being used by other generator as a way to allow users to add information (steps) on how to extend the generator without compromising its core foundation.

**Comment by juliancwirko** [comment]
I think about dropping Jade support in version 1.0.0, but it will be great if we could have support for plugins/extensions which could provide Jade, Handlebars etc. support.

**Comment by juliancwirko** [comment]
Closed for now. You can read more here: https://github.com/juliancwirko/generator-zf5/issues/41#issuecomment-146167374
