### ISSUE TITLE
Not working with Libsass

### ISSUE THREAD

**Issue by jurbank** [juliancwirko/generator-zf5#35]
If I choose the option to use Libsass within my project, I receive the following project when I run the default command 'grunt':

$ grunt
Running "sass:dist" (sass) task
Warning: app/bower_components/foundation/scss/foundation/functions:13: error: error reading values after $modules

A hack to get this to work is by removing !global from lines 13 and 17 of:
app/bower_components/foundation/scss/foundation/functions

I haven't run into problems using this method but there may be some repercussions.

**Comment by juliancwirko** [comment]
I need to update it to work with Foundation 5.5.1. I'll try to do it asap. This is probably the cause.
I will test it with new Foundation and update repo.

**Comment by juliancwirko** [comment]
Hi, now you can try with a new project. 
You can run ````bower cache clean```` before.

**Comment by jurbank** [comment]
Works great for me. Thanks!
