### ISSUE TITLE
How can I disable livereload completely? (too slow)

### ISSUE THREAD

**Issue by pickledegg** [juliancwirko/generator-zf5#39]
The livereload is taking 5-6 seconds to cycle. I've tried the ruby and libsass versions and there doesn't appear to be a big difference. HTML changes are very fast, but the SCSS changes are the killer. 

Whats the easiest way to disable this?

**Comment by juliancwirko** [comment]
Hi, you can remove/set up to false ````livereload```` in Gruntfile.js: ```watch``` section and ````connect```` section.
