### ISSUE TITLE
Getting a package.json error when trying to load a new project

### ISSUE THREAD

**Issue by xtianus79** [juliancwirko/generator-zf5#40]
error prevents loading.

**Comment by juliancwirko** [comment]
Hi, could you provide some more information? 
Steps to reproduce etc.
Thanks.

**Comment by xtianus79** [comment]
upon entering through git bash version 1.95 ruby... I enter: 

npm install -g yo

and it gives this initial error warning: 

node >= 0.10.0, npm >= 2.1.0 current 0.10.33 and npm 1.4.28 err failed to parse json tell package author to fix their json

**Comment by juliancwirko** [comment]
It occures when you run ````npm install -g yo```` or ````npm install -g generator-zf5```` ?
Because ````yo```` is unrelated with generator on the installation stage.

**Comment by xtianus79** [comment]
ok just a little update... the error was from my side. I updated my node... then my npm broke... so I fixed that too... now everything is working great.  p.s. are you still interested in the Visual Studio project?

**Comment by juliancwirko** [comment]
Oh, ok. 
As regards to Visual Studio, I'm afraid I can't help you with this.

**Comment by xtianus79** [comment]
no problem... i am working on a work around where I just load your project into a VS project folder and then deal with the file from visual studio from there.  
VS has some things that will allow some organization and other sdk injections that would be neat if the two worlds could work together.  It would be a game changer for sure.  
I will keep you posted.  
Great work as always. I really appreciate what you do. 
Thanks 
Christian 

Date: Thu, 12 Mar 2015 16:20:29 -0700

**Comment by xtianus79** [comment]
julian hey how are you. I figured out how to place your project inside of visual studio.  I want to create a fork and wanted to know if you would be willing to share with me the effort.  The only thing I need to do is create an additional file called index.cshtml and _layout.cshtml which contains the header and footer information.  That's it.  
From there I will be able to do these things:
I can run your project in command line.  
I can bring over the files into Visual Studio as symbolic links per se... and fully run everything I want to in VS
I can use every command and workup you have via your instructions and it will automagically come into my VS project. 
It's amazing and I love it.  
I want to give talks about this stuff.  
would you be willing to help with those few things for the files?  

From: xtianus@live.com
To: reply@reply.github.com
Subject: RE: [generator-zf5] Getting a package.json error when trying to load a new project (#40)
Date: Thu, 12 Mar 2015 22:07:53 -0400




no problem... i am working on a work around where I just load your project into a VS project folder and then deal with the file from visual studio from there.  
VS has some things that will allow some organization and other sdk injections that would be neat if the two worlds could work together.  It would be a game changer for sure.  
I will keep you posted.  
Great work as always. I really appreciate what you do. 
Thanks 
Christian 

Date: Thu, 12 Mar 2015 16:20:29 -0700
