### ISSUE TITLE
Ideas for 1.0.0

### ISSUE THREAD

**Issue by juliancwirko** [juliancwirko/generator-zf5#41]
- generator renaming (something like generator-foundation-for-sites due to Foundation 6 and future versions)
- [browser-sync](http://www.browsersync.io/) integration
- gulp and grunt support
- eslint instead of jshint
- drop jade support (but we should have recipes for integrating such solutions)
- sub generator for new .html file
- Autoprefixer - we need tests here. It could be autoenabled in default task or separated task
- Foundation 6 architecture research
- write tests
- update yeoman-generator API usage

..you can add more. We will choose some ;)

**Comment by juliancwirko** [comment]
Hey, the new Foundation 6 will be so awesome that I have decided that there will be no generator for foundation 6 (from me at least ;)). So, very soon I will release generator-zf5 1.0 which will be always up to date with Foundation 5 (there is an info that Foundation 5 will be maintained too). I will remove Jade. All other stuff will stay the same. All mentioned new features will be postponed. PR are welcomed after version 1.0 relese. 

The new Foundation 6 'advanced' scaffold (produced by foundation CLI tool) should look very similar to generator-zf5. It probably be using Gulp instead of Grunt, but it's ok. I plan to write some articles about Foundation 6 so there will be some guidelines for those of you who used to work with generator-zf5 :)

**Comment by samvloeberghs** [comment]
Sounds good! I have done some research about Foundation 6 already. So if you need any help in thefuture, just shout and I'll be glad to help out :)

**Comment by juliancwirko** [comment]
:+1: :smiley:

**Comment by ppowalowski** [comment]
Hi @juliancwirko 
I had the plans for a while now - and finally my time and project situation allowed me to translate the generator-zf5 output to a compatible gulp implementation.

You can check it out here: (no yo generator yet).
https://github.com/ppowalowski/gulp-foundation-boilerplate

I copied my generator-zf5 project files over to this and it instantly worked out. With this we could offer generator-zf5 as grunt version or alternatively as gulp version.

What do you think?

**Comment by juliancwirko** [comment]
Cool! If you think that it is ready I could link it in the generator-zf5 docs. I'll try it asap.

I think that Libsass is so popular right now that the Yeoman wrapper is not necessary. Yeoman was usefull here because we wanted to give a choice between Ruby Sass and Libsass. I think that Libsass is the future for Sass.

**Comment by ppowalowski** [comment]
Great, I stumbled into some issues which I am cleaning out right now. I'll inform you as soon as it's up and running.

**Comment by juliancwirko** [comment]
I understand that `gulp build` is the same as `grunt publish` here... I have some problems with `Promise is not defined` but I think it is because I have old Node 0.10.37

**Comment by ppowalowski** [comment]
Yes, we can rename `build` to `publish` though

I'm fighting a similar issue. Yesterday I sent a pull request to [gulp-usemin](https://github.com/zont/gulp-usemin) and I am trying to figure out why usemin fails to link assets properly.
