### ISSUE TITLE
npm instalation wargnins

### ISSUE THREAD

**Issue by SalahAdDin** [juliancwirko/generator-zf5#42]
Please, see this:
```bash
tulipan@tulipan-Satellite-M645:~$ sudo npm install -g generator-zf5
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-zf5 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
```
Installed with:
```bash
tulipan@tulipan-Satellite-M645:~$ nodejs -v
v0.12.7
tulipan@tulipan-Satellite-M645:~$ npm -v
2.11.3
```

**Comment by juliancwirko** [comment]
Yes, I think I should update package.json. But those warnings shouldn't block you.

**Comment by SalahAdDin** [comment]
It's easy solve this:
```bash
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
```

**Comment by juliancwirko** [comment]
There is an updated version 0.9.10

**Comment by SalahAdDin** [comment]
Well, but, show me yet:
```bash
tulipan@tulipan-Satellite-M645:~$ sudo npm install -g generator-zf5
[sudo] password for tulipan: 
npm WARN peerDependencies The peer dependency yo@~1.4.7 included from generator-zf5 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

```

**Comment by juliancwirko** [comment]
Hey, I think this is an OS specific problem. Something related with npm versions maybe. I don't see it on Ubuntu with npm v0.10.37, despite this, it should work, these are only warnings. I'll try to figure it out. Also take a look at these comments here: http://julian.io/foundation-5-and-yeoman/#comment-2177453598 I think it could be related.

**Comment by SalahAdDin** [comment]
tulipan@tulipan-Satellite-M645:~$ node -v
v0.12.7
tulipan@tulipan-Satellite-M645:~$ npm -v
2.13.4

**Comment by SalahAdDin** [comment]
Man please, update the requirements for FontAwesome 4.4 and jquery-placeholder 2.1.2.

Thanks!

**Comment by juliancwirko** [comment]
It is updated for FontAwesome 4.4 (https://github.com/juliancwirko/generator-zf5/blob/master/app/templates/bower.json) and jquery-placeholder comes from Foundation bower package

**Comment by SalahAdDin** [comment]
:+1: it's right, thank you!

**Comment by juliancwirko** [comment]
I close it for now.

**Comment by SalahAdDin** [comment]
Why?

**Comment by juliancwirko** [comment]
I don't see this problem, and nobody commented here neither. I think it is a matter of OS settings. Also this issue hasn't clean description.
