### ISSUE TITLE
Gruntfile Excludes? *Question*

### ISSUE THREAD

**Issue by wootencl** [juliancwirko/generator-zf5#43]
Why the exclude of foundation in the wiredep? Apologize in advance if there is an obvious answer to this question. Absolutely new to using Grunt. Beyond that though thanks for the awesome project! 

EDIT: Please ignore this question. I'm not a smart person. Figured it out afterwards. Thanks again for the project!

**Comment by juliancwirko** [comment]
Hi, because we have our own foundation includes config here: https://github.com/juliancwirko/generator-zf5/blob/master/app/templates/index.html#L963 we don't want Bower to include the foundation automatically
