### ISSUE TITLE
Jade:Compile aborted

### ISSUE THREAD

**Issue by woeps** [juliancwirko/generator-zf5#44]
Hi!
First, I'd like to say I really appreciate the work done on this generator. I'm just getting to the bottom of yeoman etc, but I do see a lot of potential in this generator streamlining the developement-process and I'm going to use this a lot in the future.

After a fresh install and setup I tried the generator (font awesome & compass enabled) and it worked perfectly fine, but when I tried to use the generator with jade-templates enabled `grunt` aborted while compiling whith the following output:
```
Running "jade:compile" (jade) task
>> TypeError: app/bower_components/modernizr/test/browser/integration.jade:34
>>     32|       };
>>     33|       mocha.setup('bdd').timeout(20000);
>>   > 34|     each test in integrationTests
>>     35|       script(src='../'+test)
>>     36|     script(src='../node_modules/json3/lib/json3.min.js')
>>     37|     script(src='../node_modules/expect.js/index.js')
>> 
>> Cannot read property 'length' of undefined
Warning: Jade failed to compile "app/bower_components/modernizr/test/browser/integration.jade". Use --force to continue.

Aborted due to warnings.
```

Now I allready read Jade-Support is gonna be dropped for the 1.0-release and I do know it was only experimental.
I also don't necessarily need Jade but I'd be thankfull for any advice on this. - I'm kind of lost here, due to my very vew experiences with yeoman.

**Comment by juliancwirko** [comment]
Hi, yes I plan to drop the Jade support. I will try to debug this particular problem soon. Anyway soon there will be Foundation 6 with [assemble](http://assemble.io/) support. I think it will be better toolset and Jade will be not needed here. I think I will try to close generator-zf5 without Jade. I don't know if I will be releasing Yeoman generator for Foundation 6. I am sure that there will be many better options for it.

**Comment by juliancwirko** [comment]
I close it for now. There will be no Jade support in version generator-zf5 1.0.0. You can read more here: https://github.com/juliancwirko/generator-zf5/issues/41#issuecomment-146167374

**Comment by CharlieGreenman** [comment]
Just going back to what you mentioned about assemble, why would assemble, which is a static site generator, replace Jade which is a templating system?

**Comment by juliancwirko** [comment]
I mean that assemble is ready to use tool which provides templating engine. Also I think that Jade could be integrated with assemble. In default there is a handlebars templating system. Anyway I am not sure if there will be assemble in Foundation 6. There is a tool called [panini](https://github.com/zurb/panini) which could do similar work. There will be some advanced scaffold in Foundation 6 which will provide many cool features.

**Comment by CharlieGreenman** [comment]
Okay, while we are going the gulp route definitely, may I suggest we look into slush(http://slushjs.github.io/#/) for next gen. I am working with it now for this build(https://github.com/CharlieGreenman/webpack-gulp-babel-the-works) and it seems promising. 

--> If you would like me to move this to a new issue by all means, I would be more than happy to do so. Thanks!

**Comment by juliancwirko** [comment]
I don't plan to create a generator for F6. I hope that the tools provided by foundation team will be much better.

**Comment by CharlieGreenman** [comment]
Cool cool. Thanks for schmoozing ;)
