### ISSUE TITLE
(duplicate) field in package.json template

### ISSUE THREAD

**Issue by chrisvogt** [juliancwirko/generator-zf5#45]
I am about to submit a pull request for a duplicate `description` field in the package.json template. I replaced it with a blank `license` field.

_Current:_
```json
{
  "name": "zf5_project",
  "description": "",
  "version": "0.0.1",
  "description": "",
```

_New:_
```json
{
  "name": "zf5_project",
  "description": "",
  "version": "0.0.1",
  "license": "",
```

**Comment by juliancwirko** [comment]
Hey, thanks. 
I will merge it tomorrow.

**Comment by chrisvogt** [comment]
Thank you for the generator. I have used it a few times recently and enjoy how it is organized. :+1:
