### ISSUE TITLE
modernizr.min.js is empty!

### ISSUE THREAD

**Issue by samarthmshah** [juliancwirko/generator-zf5#47]
Hello,

There is a problem that I have been facing constantly.

While setting up the zf5 scaffold, I kept the option for modernizr *on*. 

But it seems that modernizr is having some issues. When I run ``grunt publish`` and ``grunt server-dist`` the ``modernizr.min.js`` is completely empty - which is why I cannot use most Foundation features.

Has anyone else faced any problem?

**Comment by juliancwirko** [comment]
Hey, I will test it asap.

**Comment by juliancwirko** [comment]
Ok, in version 0.10.0 there is an implementation of [grunt-modernizr](https://github.com/modernizr/grunt-modernizr) so you will have only needed features in modernizr custom build. Let me know if this will work for you.

**Comment by samarthmshah** [comment]
Hello, 

Still doesn't work properly.

I had a lot built based on this generator already, so I couldn't just delete and update my zf5 scaffold to 0.10.0.

But, what I did is:

1. Made changes to ``Gruntfile.js``:

Added this:
```javascript
 modernizr: {
            dist: {
                'dest': '<%= dist %>/js/modernizr-custom.js'
            }
        }
```

Modified these two lines:

```javascript
grunt.registerTask('default', ['compile-sass', 'bower-install', 'modernizr:dist', 'connect:app', 'watch']);
grunt.registerTask('publish', ['compile-sass', 'modernizr:dist', 'clean:dist', 'validate-js', 'useminPrepare', 'copy:dist', 'newer:imagemin', 'concat', 'cssmin', 'uglify', 'usemin']);
```


2. On my Command line:

```sh
$ npm install grunt-modernizr --save-dev
```

3. Deleted the ``modernizr`` dependency from my ``bower.json``. Deleted modernizr from ``bower_components``

4. In my index.html, changed these two lines:

I had a question here: I dont have anything like modernizr-custom.js in my js/ folder? Wouldn't this give an error 404?

```html
<!-- build:js js/vendor/modernizr-custom.min.js -->
<script src="js/modernizr-custom.js"></script>
```

5. Now when I run 

```sh
$ grunt
```

It threw this error:

```sh
Running "wiredep:target" (wiredep) task
Warning: Error: modernizr is not installed. Try running `bower install`. Use --force to continue.
```

6. So I do as they say:

```sh
$ bower install
```

Which I have no idea how installs modernizr magically (**Even when I deleted it as a dependency from ``bower.json``**.

Having modernizr in my bower_components now, I run ``grunt`` command again, it does everything and again, 

When I run my website, I get these errors:

* see modernizr error *.

<img width="1440" alt="screen shot 2015-10-04 at 6 49 54 pm" src="https://cloud.githubusercontent.com/assets/10097486/10270727/c066f29e-6ac8-11e5-95d1-f18832eff34b.png">


Can you tell me whats wrong?
Seems like Foundation is relying a lot on Modernizr and hence im not able to use most things like ``tooltip`` for example.

**Comment by juliancwirko** [comment]
Bower installs it because there is another bower config in the Foundation. But we don't want to use it here. You can check if you have `grunt-modernizr` in your `package.json` file and run `npm update`. It looks like your `modernizr:dist` task not work at all. When you run `grunt` there should be created `modernizr-custom.js` file in the `js` folder. Maybe there is a bug somewhere in the `Gruntfile.js` it is hard to say. You can send me your Gruntfile.js and I will try to tell you more.

**Comment by samarthmshah** [comment]
It is in the ``package.json`` file. Also ran ``npm update``. 

I have my project here on Github only, you can check my Gruntfile.js

https://github.com/samarthmshah/portfolio-template/blob/master/Gruntfile.js

**Comment by juliancwirko** [comment]
OK, I'm going to look at it now.

**Comment by juliancwirko** [comment]
Oh I can see now... there is one trick here. 
You have used:
```
modernizr: {
            dist: {
                'dest': '<%= dist %>/js/modernizr-custom.js'
            }
        }
```
and it should be:
```
modernizr: {
            dist: {
                'dest': '<%= app %>/js/modernizr-custom.js'
            }
        }
```
So instead `dist` it should be `app` in the path. This is because it needs it in the app folder and then the build process will copy it into dist folder. I know that this is not so intuitive (maybe I should change names), but we need this file in the app and later in the dist folder too (but it will be done by build task)

Try changing it and let me know if this helps.

**Comment by samarthmshah** [comment]
Nope, still not working.

Still throws error here:

<img width="702" alt="screen shot 2015-10-06 at 8 28 22 am" src="https://cloud.githubusercontent.com/assets/10097486/10308525/4020631c-6c04-11e5-8f8f-e732fd156b9e.png">


I guess Foundation and all those apps are trying to find modernizr in bower_components and don't find it.

Also, doesn't it make more sense to have modernizr in the bower_components?

I don't know, maybe you don't need to use ``grunt-modernizr`` at all. Maybe there was some problem with ``bower`` not properly installing modernizr?

**Comment by juliancwirko** [comment]
I don't know :/ I can't find compiled modernizer in bower_components there is something changed in the files structure and grunt-modernizr will build only what you need. 

You have this error from wiredep because you probably need to exclude modernizer like:

```
wiredep: {
			target: {
				src: [
					'<%= app %>/**/*.html'
				],
				exclude: [
                                        'modernizr',
					'font-awesome',
					'jquery-placeholder',
					'foundation'
				]
			}
		},
```
You don't want the modernizer here because it has its own task.
also remember to leave the 'app' variable in the path in medernizr task.

**Comment by samarthmshah** [comment]
Yeah, I thought so. ``bower_components/modernizr/src/Modernizr.js`` also can't compile. Ultimately, modernizr just doesnt run anyhow.

And yes, I have excluded modernizr from my wiredep.

```javascript
wiredep: {
			target: {
				src: [
					'<%= app %>/**/*.html'
				],
				exclude: [
                    'modernizr',
					'font-awesome',
					'jquery-placeholder',
					'foundation'
				]
			}
		}
```

AND..

```javascript
modernizr: {
            dist: {
                'dest': '<%=app%>/js/modernizr-custom.js'
            }
        }
```

**Comment by juliancwirko** [comment]
Ok, I will try to clone you project and I will test it live.

**Comment by samarthmshah** [comment]
Great, lemme push the latest one.

**Comment by samarthmshah** [comment]
Here you go: https://github.com/samarthmshah/portfolio-template.git

**Comment by juliancwirko** [comment]
Ok, give me couple of hours.

**Comment by juliancwirko** [comment]
Hey, this is weird but it works good for me. I have cloned it and then `npm install` and `bower install` when I run `grunt` or `grunt build` it works as it suposed to.

Maybe try to remove node_modules and bower_components folders and try to run npm install and bower install. Or try in a new directory.

**Comment by samarthmshah** [comment]
So weird.

Haha.

I deleted the project, cloned it again, works for me too. I guess twas a ``node_modules`` and ``bower_components`` issue.

Note: We are still using ``modernizr`` in ``bower_components`` because ``Foundation`` is dependent on it. And we have grunt-modernizr too in our node_modules.

Thanks for all the help :+1:

**Comment by juliancwirko** [comment]
Yes, modernizr will be downloaded by bower because of foundation settings. But I don't think that this is a very big problem. It is 'build' what matters after all.

**Comment by juliancwirko** [comment]
ops I think that there is an update included this problem too. I will try to update zf5 tomorrow. http://foundation.zurb.com/forum/posts/35471-foundation-553-is-has-been-released

**Comment by samarthmshah** [comment]
Thats why. Now it makes sense !

On Tue, Oct 6, 2015, 5:09 PM Julian Ćwirko <notifications@github.com> wrote:

> ops I think that there is an update included this problem too. I will try
> to update zf5 tomorrow.
> http://foundation.zurb.com/forum/posts/35471-foundation-553-is-has-been-released
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/juliancwirko/generator-zf5/issues/47#issuecomment-146001733>
> .
>
-- 
Best,
Samarth Shah
URL: http://samarth.xyz
Phone: 5184280722

**Comment by juliancwirko** [comment]
I think I'll back to the previous solution if only there will be builded modernizr in the bower_components. This is not so big file and the build process with `grunt-modernizr` is now longer.

**Comment by samarthmshah** [comment]
Yeah check if we really need grunt-modernizr. I think they should have
fixed the bower_components thing.

On Tue, Oct 6, 2015, 5:21 PM Julian Ćwirko <notifications@github.com> wrote:

> I think I'll back to the previous solution if only there will be builded
> modernizr in the bower_components. This is not so big file and the build
> process with grunt-modernizr is now longer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/juliancwirko/generator-zf5/issues/47#issuecomment-146005703>
> .
>
-- 
Best,
Samarth Shah
URL: http://samarth.xyz
Phone: 5184280722
