### ISSUE TITLE
Foundation sites 6

### ISSUE THREAD

**Issue by SalahAdDin** [juliancwirko/generator-zf5#49]
Are you thinking give foundations sites 6 support or create a generator for zfs6?

**Comment by juliancwirko** [comment]
Hi, no, there will be no zf6 :) New starter kits from Foundation are awesome :) You can read about it on my blog: http://julian.io/what-i-like-the-most-about-the-new-foundation-6/ 

I help them with Meteor package and maybe in the future also with starter kits, we will see :)

**Comment by SalahAdDin** [comment]
Ok, thanks, i have to migrate all my entire project.
