### ISSUE TITLE
Wiredep not working as expected out of the box

### ISSUE THREAD

**Issue by njradford** [juliancwirko/generator-zf5#50]
On OSX Yosemite, after running the generator and running the default Grunt task, the Foundation demo page is missing it's jQuery reference due to the wiredep process not including it in the bower tags at the footer of index.html. It is, of course, an easy fix to include the jQuery script tag myself, but seems like something that is getting skipped due to a quiet background issue.

**Comment by juliancwirko** [comment]
It worked, but maybe there was some changes. I'll update all the dependencies and then I'll test it asap.
